(library
 (name bounty)
 (public_name bounty)
 (modules bounty)
 (preprocess (pps ppx_deriving_encoding ppx_deriving_jsoo))
 (libraries ez_api.encoding_js peerJS uuidm)
 (modes byte))

(library
 (name ui)
 (public_name bounty.ui)
 (modules db back ui)
 (wrapped false)
 (preprocess (pps ppx_deriving_jsoo vue-ppx))
 (libraries bounty sync.idb sync.peerjs)
 (modes byte))

(executable
 (name app)
 (modules
   navigation settings app
   adventures adventure newAdventure joinAdventure
   loot newLoot)
 (preprocess (pps ppx_deriving_jsoo vue-ppx))
 (preprocessor_deps
   navigation.html settings.html
   adventures.html adventure.html newAdventure.html joinAdventure.html
   loot.html newLoot.html)
 (libraries ui)
 (modes js))

(install
 (package bounty)
 (section share)
 (files index.html app.bc.js manifest.json sw.js))
